run:
  timeout: 5m

linters:
  enable:
    - gocritic
    - gofmt
    - gosec
    - lll
    - misspell
    - nakedret
    - scopelint
    - unconvert
    - unparam

gocritic:
  enabled-checks:
    - typeUnparen

  enabled-tags:
    - performance
    - style
