builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}"
    files:
      - none*

checksum:
  name_template: checksums.txt

release:
  github:
    owner: pmaene
    name: fail2ban_exporter

dockers:
  - image_templates:
      - pmaene/fail2ban_exporter:latest
      - pmaene/fail2ban_exporter:v{{ .Version }}
