builds:
  - env:
      - CGO_ENABLED=0

    goos:
      - linux

    goarch:
      - amd64
      - arm
      - arm64

    goarm:
      - 6
      - 7

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - none*

checksum:
  name_template: checksums.txt

release:
  github:
    owner: pmaene
    name: fail2ban_exporter
