pull_request_rules:
  - name: Automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - status-success=GolangCI-Lint
    actions:
      merge:
        method: rebase
